### ISSUE TITLE
Ignore Methods not Supported or Support RegExp Validation

### ISSUE THREAD

**Issue by FlorianWendelborn** [woutervh-/typescript-is#16]
I just tried to validate that one of my optional config variables is a `RegExp`. `typescript-is` complained and told me:

> `Error: Encountered a method declaration, but methods are not supported. Please check the README`

Would it be possible to either support `RegExp`, or to opt-out of this error explicitly in the `is<...>(...)`?

**Comment by woutervh-** [comment]
Hi @FlorianWendelborn 

I understand you're trying to validate an object that has a RegExp type property.
Classes are not supported, and because RegExp is a class, it's also not supported.
That being said, I'm not sure why the error message is about a "method" and not a "class", this is something I will investigate.
I also think adding an option to ignore classes/methods/RegExp/Date etc. is a good idea.
So I will be adding the option to ignore those rather than throw an error.

Will keep you updated.

Thanks!

**Comment by woutervh-** [comment]
Foot note 1: `typescript-is` mainly focuses on validation serializable data. Since a RegExp class is generated at runtime, it's somewhere in the code, and that means it should have a type. Is there a reason why the type is lost somewhere in your code?
Foot note 2: if the RegExp is encoded as a string then it becomes serializable and then `typescript-is` can check if it's a string.

**Comment by woutervh-** [comment]
Hi @FlorianWendelborn 

I've added the following options: `ignoreClasses`, `ignoreMethods`
The latter is needed for skipping `RegExp` validation.

Version: `0.10.2`
Documentation: https://github.com/woutervh-/typescript-is#options

Let me know if this works for you.

**Comment by woutervh-** [comment]
Closing for house keeping.
