### ISSUE TITLE
Problem with Date

### ISSUE THREAD

**Issue by zdila** [woutervh-/typescript-is#29]
```typescript
interface IDevice {
  createdAt: Date;
}

const foo = { createdAt: new Date() } as any;
assertType<IDevice>(foo);
```

This causes:

```
Error: Encountered a method declaration, but methods are not supported. Issue: https://github.com/woutervh-/typescript-is/issues/5
```

**Comment by woutervh-** [comment]
hi @zdila 
Indeed classes and methods cannot be checked.
If, for some reason, you can't avoid classes or methods in your types, you can check out the options added from this issue:
https://github.com/woutervh-/typescript-is/issues/16
or here: https://github.com/woutervh-/typescript-is#options

**Comment by zdila** [comment]
Hi @woutervh-,

I've tried `ignoreClasses` but got the same error. Still I think it would be nice to support at least JS built-in objects (like `Date`, `RegExp`, `Set`, `Map`, ...).

What do you think?

**Comment by woutervh-** [comment]
Hi @zdila 
Actually when you take a look at the Typescript definition of Date, you'll see it's an interface with methods (yeh, don't ask, it's strange 😵). So to get around `Date` you would need to use `ignoreMethods`.
I will consider supporting popular built-in classes like `Date` and `RegExp`. If it turns out to be easy to support them I will do that.
Will update you when I look into it.

**Comment by woutervh-** [comment]
Closing for house keeping.
