### ISSUE TITLE
Generic assertType results in "Unbound type parameter, missing type node."

### ISSUE THREAD

**Issue by ArthurClemens** [woutervh-/typescript-is#32]
This is a similar issue to #4. In my case I am getting the error when trying to use `assertType<T>(data)`

```ts
async function fetchContent<T>(filename: string): Promise<boolean> {
  const url = `/${filename}`;
  const res = await fetch(url);
  const data = await res.json();

  try {
    assertType<T>(data);
    return true;
  } catch (error) {
    console.log(error.message);
    return false;
  }
}

fetchContent<CMS.Homepage>('homepage.json');
```

**Comment by woutervh-** [comment]
Hi @ArthurClemens

In this case it is intended behavior.

The type that is being checked must be a real type, not a type parameter that is not bound to anything, at the call site of the `assertType` function.

This is the relevant part in the Readme:
https://github.com/woutervh-/typescript-is/blob/master/README.md#-what-it-wont-do

It is different from #4 because that issue is about a type with parameters that were well defined at the call site.

The reason that it cannot be done is because the transformer will generate the code for the type in the function call and it cannot do that for a parameter type `T` which can be anything. 

I suggest you do the type check where you already have the interface `CMS.Homepage` and keep the return type of the fetch function `unknown`.

Hope this helps.

**Comment by ArthurClemens** [comment]
Thanks for the clarification.
