### ISSUE TITLE
Possibility to use with react-scripts

### ISSUE THREAD

**Issue by kneczaj** [woutervh-/typescript-is#36]
Hello!

I use react-scripts to set up my react project. It would be nice to use typescript-is with it without "ejecting". For the first trial I have added the `plugins` section in my `tsconfig.json`.

Unfortunately, I've got this error:
```
Error: This module should not be used in runtime. Instead, use a transformer during compilation.
```

Do you have any information what to do when I want to use it with react-scripts?

**Comment by woutervh-** [comment]
hi @kneczaj 

The problem is caused because the project is compiled with the regular `typescript` compiler.
For the transformation to take place, you need to compile the project with `ttypescript` (or set up your own compile scripts).

I'm not too familiar with `react-scripts` but I think other people have had similar issues.

In issue #33 someone had a similar problem and it was solved by avoiding the type guard during development.
The idea is that you use `setDefaultGetErrorMessage` to always return `null` during development.
When you "eject" you remove the use of `setDefaultGetErrorMessage`.

In the end if you want to use the transformation before ejecting, you will need to convince the `react-scripts` configuration somehow to use `ttypescript` as the compiler.

**Comment by woutervh-** [comment]
Closing for housekeeping.
