### ISSUE TITLE
Methods are not ignored in mapped types (maked with keyof syntax)

### ISSUE THREAD

**Issue by SteMab** [woutervh-/typescript-is#50]
Since at the moment typescript-is does not support using `is<T>()` when T is a class, I have used a mapped type as this:

```
class MyClass {
    method() : string {
        return "";
    };
}

type MappedType = {
    [P in keyof MyClass]: MyClass[P];
}
```

but typescript-is does not check properly MappedType and throws a error, though the flag "ignoreMethods" is true: it not ignore the method, but expect the property contains an object:

```
let mappedType : MappedType = {
    method() {
        return "!!!";
    }
};

assertType<MappedType>(mappedType);
```

error log:

> TypeGuardError: validation failed at $.method: expected an object
>     at Object.assertType (...\node_modules\typescript-is\index.js:62:15)
>     at Object.<anonymous> (...\my_test.js:10:21)
>     at Module._compile (internal/modules/cjs/loader.js:736:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
>     at Module.load (internal/modules/cjs/loader.js:628:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:560:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
>     at executeUserCode (internal/bootstrap/node.js:526:15)
>     at startMainThreadExecution (internal/bootstrap/node.js:439:3)

**Comment by woutervh-** [comment]
Hi @SteMab 

There are two things going on that are causing the issue:

1. When you write `type MappedType = { [P in keyof MyClass]: MyClass[P]; }`, TypeScript does not keep `method` as an actual method. Instead, it becomes a regular object property with a function type. You can see this if you inspect the type `MappedType`, it will have the property `method` as a function: `method: () => string`.

2. Because of this, `ignoreMethods` will not be checked to decide to ignore this property. `typescript-is` is now working with a regular function, and because these are not supported, its behavior is undefined.

To solve this:

1. I can add a new option `ignoreFunctions` with similar behavior as `ignoreMethods` but will work for any function.

2. You can avoid using `assertType` on classes/functions/methods. Since you have a class instance, why not use `instanceof`?

**Comment by SteMab** [comment]
@woutervh- Thank you for your kind reply which clarified the point.
I can't use instanceof because I'm writing an http firebase function and the object to check was been serialized.

An option ignoreFunctions would be useful, in my opinion (but I'm not familiar with typescript and prototype-based programming).

**Comment by woutervh-** [comment]
Hi @SteMab 

I've added the option `ignoreFunctions`:
https://github.com/woutervh-/typescript-is/releases/tag/v0.14.3
https://github.com/woutervh-/typescript-is#options

Let me know if this helps :)

**Comment by SteMab** [comment]
The new option `ignoreFunctions` has solved my problem. Thanks so much

**Comment by ivarne** [comment]
Found this from the link in the error message and want to leave a note that `ignoreFunctions` is deprecated and you can now declare `functionBehavior: "basic"` instead.
